import {loadTimeData} from '//resources/js/load_time_data.js';
loadTimeData.data = {
    "addLinkTitle": "Add shortcut",
    "audioError": "Please check your microphone.",
    "backgroundColor": "#3C3C3C",
    "backgroundImageUrl": "",
    "calendarModuleDismissHours": "12",
    "close": "Close",
    "colorPickerLabel": "Custom colour",
    "controlledSettingPolicy": "This setting is managed by your administrator.",
    "copyLink": "Copy link",
    "customizeButton": "Customise Chrome",
    "customizeThisPage": "Customise this page",
    "customizeThisPageWallpaperSearch": "Customise this page with AI",
    "details": "Details",
    "disableModuleToastMessage": "You won't see $1 on this page again",
    "dismissModuleToastMessage": "$1 hidden",
    "doneButton": "Done",
    "doodleLink": "Doodle Link",
    "editLinkTitle": "Edit shortcut",
    "email": "Email",
    "facebook": "Facebook",
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "googleBaseUrl": "https://www.google.com/",
    "hideSuggestions": "Hide suggestions",
    "hueSliderAriaLabel": "Hue slider from $1 to $2",
    "hueSliderTitle": "Colour picker",
    "invalidUrl": "Type a valid URL",
    "isLensSearchbox": false,
    "language": "en",
    "languageError": "Voice search in your language is not available.",
    "learnMore": "Learn more",
    "learnMoreA11yLabel": "Learn more about using a microphone",
    "lensSearchButtonLabel": "Search by image",
    "lensSearchUploadDialogCloseButtonLabel": "Close",
    "lensSearchUploadDialogDragDropTitle": "Drop an image here",
    "lensSearchUploadDialogDragTitle": "Drag an image here or",
    "lensSearchUploadDialogErrorFileSize": "Can't upload. Use an image smaller than 20 MB.",
    "lensSearchUploadDialogErrorFileType": "Can't upload. Use an image in one of these formats: .jpg, .gif, .png, .bmp, .tif or .webp",
    "lensSearchUploadDialogErrorMultipleFiles": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogErrorMultipleUrls": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogLoadingText": "Uploading…",
    "lensSearchUploadDialogOfflineButtonLabel": "Try again",
    "lensSearchUploadDialogOfflineSubtitleText": "Please check your Internet connection and try again",
    "lensSearchUploadDialogOfflineText": "No network connection",
    "lensSearchUploadDialogOrText": "OR",
    "lensSearchUploadDialogSearchButtonLabel": "Search",
    "lensSearchUploadDialogTextPlaceholder": "Paste image link",
    "lensSearchUploadDialogTitle": "Search any image with Lens",
    "lensSearchUploadDialogUploadFileTitle": "upload a file",
    "lensSearchUploadDialogValidationErrorConformance": "Can't use this link. Check for typos or use another link to try again.",
    "lensSearchUploadDialogValidationErrorScheme": "Can't use this link. Check that your link starts with 'http://' or 'https://' to try again.",
    "linkAddedMsg": "Shortcut added",
    "linkCancel": "Cancel",
    "linkCantCreate": "Can't create shortcut",
    "linkCantEdit": "Can't edit shortcut",
    "linkDone": "Done",
    "linkEditedMsg": "Shortcut edited",
    "linkRemove": "Remove",
    "linkRemovedMsg": "Shortcut removed",
    "listening": "Listening…",
    "logoEnabled": true,
    "middleSlotPromoDismissalEnabled": true,
    "middleSlotPromoEnabled": true,
    "mobilePromoDescription": "Download Chrome for iOS to access your tabs, bookmarks and passwords on your phone.",
    "mobilePromoEnabled": false,
    "mobilePromoHeader": "Get Chrome on your mobile device",
    "mobilePromoQrCode": "Scan QR Code",
    "moduleGoogleCalendarInfo": "You're seeing your calendar to help you easily navigate to your next event in Google Calendar.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "moduleHeaderMoreActionsMenu": "More actions",
    "moduleInfoButtonTitle": "About this card",
    "modulesCalendarInProgress": "In progress",
    "modulesCalendarInXHr": "In $1 hr",
    "modulesCalendarInXMin": "In $1 min",
    "modulesCalendarJoinMeetingButtonText": "Join meeting",
    "modulesCalendarSeeMore": "See more",
    "modulesCustomizeButtonText": "Customise cards",
    "modulesDisableButtonText": "Never show $1",
    "modulesDisableButtonTextV2": "Don't show $1",
    "modulesDisableToastMessage": "You won't see $1 again",
    "modulesDismissButtonText": "Hide $1",
    "modulesDismissForHoursButtonText": "Hide for $1 hours",
    "modulesDragAndDropEnabled": false,
    "modulesDriveDisableButtonText": "Never show Drive files",
    "modulesDriveDisableButtonTextV2": "Don't show Drive",
    "modulesDriveDismissButtonText": "Hide these files",
    "modulesDriveFilesSentence": "Files",
    "modulesDriveInfo": "You’re seeing suggested files to help you easily get back to your most recent activity in Google Drive.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesDriveMoreActionsButtonText": "More actions for Google Drive files",
    "modulesDriveSentence": "Google Drive files",
    "modulesDriveSentence2": "Drive files",
    "modulesDriveTitle": "From your Google Drive",
    "modulesDriveTitleV2": "From your Drive",
    "modulesDummyLower": "this module",
    "modulesDummyTitle": "Super Duper Module",
    "modulesEnabled": false,
    "modulesGoogleCalendarDisableButtonText": "Don't show Google Calendar",
    "modulesGoogleCalendarDisableToastMessage": "You won't see Google Calendar on this page again",
    "modulesGoogleCalendarDismissToastMessage": "Google Calendar hidden",
    "modulesGoogleCalendarMoreActions": "More actions for Google Calendar",
    "modulesGoogleCalendarTitle": "Google Calendar",
    "modulesHeaderIconEnabled": true,
    "modulesHistoryDoneButton": "Mark as done and hide",
    "modulesHistoryResumeBrowsingForTitle": "Resume browsing for $1",
    "modulesHistoryResumeBrowsingTitle": "Resume browsing",
    "modulesHistoryWithDiscountInfo": "You’re seeing suggested searches and shopping discounts that might interest you based on your recent activity.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from this card at any time or see more options in Customise Chrome.",
    "modulesJourneyDisable": "this card",
    "modulesJourneysBookmarked": "Bookmarked",
    "modulesJourneysDismissButton": "No longer interested",
    "modulesJourneysInfo": "You’re seeing pages you've visited and suggested searches to help you easily get back to your most recent activity.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesJourneysOpenAllInNewTabGroupButtonText": "Open all in new tab group",
    "modulesJourneysSearchSuggAcc": "Search for $1",
    "modulesJourneysShowAll": "Show all",
    "modulesJourneysShowAllAcc": "Show all searches for $1",
    "modulesJourneysShowAllButton": "Open in side panel",
    "modulesKaleidoscopeTitle": "Top picks for you",
    "modulesLoadEnabled": false,
    "modulesLoadTimeout": 3000,
    "modulesMaxColumnCount": 3,
    "modulesMoreActions": "More actions for $1",
    "modulesMostRelevantTabResumptionDismissAll": "Hide these tabs",
    "modulesMostRelevantTabResumptionFrequentlyVisited": "You visit often",
    "modulesMostRelevantTabResumptionMostRecent": "Your most recent tab",
    "modulesMostRelevantTabResumptionSeeMore": "See more",
    "modulesMostRelevantTabResumptionTitle": "Continue with these tabs",
    "modulesMostRelevantTabResumptionVisitedXAgo": "You visited",
    "modulesOutlookCalendarDisableButtonText": "Don't show Outlook Calendar",
    "modulesOutlookCalendarTitle": "Outlook calendar",
    "modulesOverflowScrollbarEnabled": true,
    "modulesRedesignedEnabled": true,
    "modulesSharepointInfo": "You’re seeing suggested files to help you easily get back to your most recent activity in Microsoft Sharepoint.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesSharepointTitle": "From your Microsoft Sharepoint",
    "modulesTabResumptionDevicePrefix": "From your",
    "modulesTabResumptionDismissButton": "No longer interested",
    "modulesTabResumptionInfo": "You're seeing tabs from other devices to help you get back to your most recent activity easily.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesTabResumptionSentence": "Tabs",
    "modulesTabResumptionTitle": "Tabs from other devices",
    "modulesTasksInfo": "You're seeing this item based on your previous activity using Google services. You can see your data, delete it and change your settings at \u003Ca href=\"https://myactivity.google.com/\" target=\"_blank\">myactivity.google.com\u003C/a>.\n        \u003Cbr>\n        \u003Cbr>\n        Learn about the data that Google collects and why at \u003Ca href=\"https://policies.google.com/\" target=\"_blank\">policies.google.com\u003C/a>.",
    "modulesTasksInfoClose": "Close",
    "modulesTasksInfoTitle": "About this card",
    "modulesThisTypeOfCardText": "this type of card",
    "mostRelevantTabResumptionDeviceIconEnabled": false,
    "mostRelevantTabResumptionEnabled": false,
    "multipleLoadedModulesMaxModuleInstanceCount": 2,
    "nameField": "Name",
    "navigationStartTime": 1.732364277445856e+12,
    "networkError": "No Internet connection.",
    "noTranslation": "Didn't get that.",
    "noVoice": "Please check your microphone and audio levels.",
    "ok": "OK",
    "oneGoogleBarEnabled": true,
    "otherError": "Unknown error.",
    "permissionError": "Voice search has been turned off.",
    "preconnectStartTimeThreshold": 100,
    "prerenderOnHoverEnabled": false,
    "prerenderOnPressEnabled": true,
    "prerenderStartTimeThreshold": 300,
    "realboxIsTall": true,
    "reducedLogoSpaceEnabled": true,
    "removeSuggestion": "Remove suggestion",
    "reportMetrics": true,
    "restoreDefaultLinks": "Restore default shortcuts",
    "restoreThumbnailsShort": "Restore all",
    "searchBoxHint": "Search Google or type a URL",
    "searchBoxHintMultimodal": "Add to your search",
    "searchboxCr23SteadyStateShadow": false,
    "searchboxCr23Theming": false,
    "searchboxDefaultIcon": "//resources/cr_components/searchbox/icons/search_cr23.svg",
    "searchboxLensDirectUpload": true,
    "searchboxLensSearch": true,
    "searchboxLensVariations": "CJS2yQEIorbJAQipncoBCJOUywEIlKHLAQiFoM0BCLSezgEI0cfOAQj3yc4BCIjMzgEIx8_OAQjI0c4BCJzSzgEIstPOAQjK1M4BGPTJzQE",
    "searchboxMatchSearchboxTheme": false,
    "searchboxSeparator": " - ",
    "searchboxThumbnailLabel": "Your Google Lens selection. Press enter or backspace to delete your Google Lens selection",
    "searchboxVoiceSearch": true,
    "searchboxWidthBehavior": "wide",
    "shareDoodle": "Share Doodle",
    "shortcutAlreadyExists": "Shortcut already exists",
    "shortcutMoreActions": "More actions for $1 shortcut",
    "shortcutsEnabled": true,
    "showSuggestions": "Show suggestions",
    "singleRowShortcutsEnabled": true,
    "speak": "Speak now",
    "textdirection": "ltr",
    "themeCreatedBy": "Theme created by",
    "themeManagedDialogBody": "Your administrator has set a default theme which cannot be changed.",
    "themeManagedDialogTitle": "Theme is set by your organisation",
    "title": "New Tab",
    "tryAgain": "Try again",
    "twitter": "Twitter",
    "undo": "Undo",
    "undoDescription": "Press Ctrl+Z to undo",
    "undoDismissPromoButtonToast": "You won't see this specific message again",
    "urlField": "URL",
    "voiceSearchButtonLabel": "Search by voice",
    "waiting": "Waiting…",
    "wallpaperSearchButton": "Create theme with AI",
    "wallpaperSearchButtonAnimationEnabled": false,
    "wallpaperSearchButtonEnabled": false,
    "wallpaperSearchButtonHideCondition": 0,
    "webstoreThemesToastButtonText": "Find themes",
    "webstoreThemesToastMessage": "You can find older colours in the Chrome Web Store",
    "wideModulesEnabled": true
};
